- modules/googlecal.py
* if we did a add del or something else return after the operation is done
* always check if events list is empty and send a "no events" message if we got that far
> Small googlecal changes

- .gitignore
- Pipfile
- bot.py
- modules/cron.py
- modules/googlecal.py
- modules/ig.py
- modules/loc.py
- modules/metar.py
- modules/taf.py
- modules/teamup.py
- modules/uptime.py
- setup.cfg
flake8 tests passes
totally untested
> lint evertyhing

- modules/url.py
This will help with pages that have broken html..
Also adds few debug print statements
closes #29
> Use Beautiful Soup for content parsing

- modules/url.py
need for these methods should probably be also documented somewhere :)
> add setting methods for url module, fixes #31

- bot.py
- modules/common/module.py
- modules/common/pollingservice.py
- modules/url.py
pollservices didn't return the settings dictionary and the call to
super was missing.
> fix: persistent settings for pollservices

- bot.py
> use regex match to check if message starts with command

- bot.py
> fix: missing import of json module and broken reload_modules method

- README.md
- bot.py
- modules/apod.py
I don't know if there is any interest but I build a module to consume the latest Nasa Astronomy Picture of the Day and send it to the room.
* upload astronomy picture of the day to the room
* cache latest response
* possibility to use own api key by setting environment variable
APOD_API_KEY (default: DEMO_KEY)
> add Astronomy Picture of the Day module

- bot.py
- modules/cron.py
> Modified msgtype of send_text & send_html methods

- modules/apod.py
> add more debugging output to apod module uploading a file

- modules/url.py
Also change a few log levels and skip edited messages completely
> url module: don't spam matrix.to urls, skip edited events, fixes #98

- modules/url.py
stream the response and only read the beginning so that httpx does not try to get everything and get stuck trying to read a stream forever
> url: fix reading streaming responses forever, fixes #79

- modules/url.py
Follows googlebot useragent convention and afaik follows RFC7231
Do we want bot.owners here also? It might be useful information but do we want to keep it as a secret?
> [URL] add useragent, fixes #107

- README.md
- bot.py
This will make leaving empty rooms optional
> Added LEAVE_EMPTY_ROOMS env var

- bot.py
- modules/apod.py
- modules/url.py
Instead of checking whether or not JOIN_ON_INVITE exists, it checks if it's set to true or false.
> Re-visioned Join on Invite Environment Variable

- modules/bot.py
It's a little spammy, so now all the modules and their help dialogue are in one message
> Revisioned Module Listing

- modules/welcome_server.py
user_query_host is needed by self.get_user_list but was initialized after the call.
Moved the initialization before the call. 
Fixes #121
> KeyError on module welcome_serverfix

- README.md
- modules/wa.py
Maybe I'm just running a newer version of `wolframalpha`, but the module was checking for `== 'true'` where the wa module was returning native python bools.
Also, I switched to looping through all pods to find a result instead of hardcoding the second pod. I also fall back to the first non-empty, non-"Input" text.
Making this a draft for now, want to test a little more.
> Fix !wa module

- bot.py
Let's get rid of that longstanding `#TODO`.
> Allow passing custom power level to admin check

- modules/wa.py
> !wa: Make short response all one line

- README.md
- modules/bot.py
> !bot import export

- Pipfile
- README.md
- bot.py
- modules/apod.py
- modules/gfycat.py
- modules/giphy.py
- modules/tautulli.py
I've developed these bots for myself, please let me know if you'd like to add to the main repo
> Adding giphy, gfycat and Tautulli bot, splitted handling for image upload and send

- modules/bot.py
- modules/common/module.py
Fairly core change, would like review before merge.
> BotModule: remove can_be_disabled flag, use exception instead

- README.md
- modules/mumble.py
We've been using this a lot on [#lup-lug:jupiterbroadcasting.com](https://matrix.to/#/#lup-lug:jupiterbroadcasting.com), and I think it's worth sharing.
Based on [this script](https://gist.github.com/azlux/315c924af4800ffbc2c91db3ab8a59bc)
> Add !mumble

- README.md
- modules/spaceapi.py
Allows for polling the open/closed status of hackspaces supporting the SpaceAPI.
> added module space api

- modules/tautulli.py
I cannot identify exactly when tautulli.py broke, but this is the fix
> fix for new version of tautulli

- bot.py
> Fix upload_and_send_image error message

- README.md
- modules/inspire.py
Query a randomly generated inspirational poster from https://inspirobot.me/ upload and send to the room.
> Adding a simple module to query Inspirobot

- README.md
- modules/xkcd.py
Added a module to fetch and display comic strips from https://xkcd.com/
> Xkcd module

- README.md
- modules/status.py
a bot module to save and query per-user status messages
> Status module

- modules/status.py
minor improvement added atop yesterdays MR
> improved status list formatting (html) and added save state on clear

- README.md
- modules/wikipedia.py
Resolves #181
This module has been fully written by Github Copilot as inspired by the recent OpenAI ChatGPT trend from the only comment prompt on wikipedia.py line 7. 
Module has been simply tested against common user query and thus requires exact match against an existing article by name.
Improvement ideas: multi-language, semantic search, pretty print related pages summary.
> New module Wikipedia

- modules/wikipedia.py
Quality of life fixes
wikipedia.py: add smart trimming for extract, use redirects, use canonical URL in content, convert spaces to underscore in urls.
> wikipedia.py: fixes smart trim, redirects, canonical urls

- Pipfile
- README.md
- modules/roll.py
This change adds a module that uses the [d20](https://github.com/avrae/d20) module to do dice rolls.
> Add !roll module for dice rolling

- modules/status.py
fixes https://github.com/vranki/hemppa/issues/247 by adding a clear all admin command and a TTL for all status messages
> adding TTL to status module

- modules/status.py
> Status module improved
