- Dockerfile
Using python:3.7-slim as basimage reduces the image size to 416 MB.
> reduce size of docker image

- modules/bot.py
- modules/common/module.py
- modules/help.py
Enables all modules per default. The bot module cannot be disabled.
Modules can be configured not beeing disableable by setting the attribute `self.can_be_disabled=False`.
The module output is sorted by key now. Added the description and if the module can be disabled.
> enable modules per default

- README.md
- bot.py
Adding an optional OWNERS_ONLY environment variable will make the bot only usable to the owners list.
- A little note: It's programmed that OWNERS_ONLY must exist rather than in-taking a Boolean to determine True or False of the OWNERS_ONLY feature (see [diff](https://github.com/vranki/hemppa/pull/62/commits/4d4309531e3a115faf2c6e2dc5325ae38e79b3b0#diff-f289368d1ae6d2d58bec9f799832d932R301))
> Added whitelisting feature

- README.md
- modules/cmd.py
Differences:
- Shell commands being evaluated no longer need to use quotation marks. This allows users to more conveniently add quotation marks to their command body
> CMD module refactor

- Pipfile
- README.md
Currently there is no way of defining >3.6 or similar in Pipfile (see https://github.com/pypa/pipenv/issues/1050)
But the requirement can be removed completely. The only downside is that someone with only python2.7 on their machine will get other errors if pipenv tries to use 2.7.
> Relax Pipfile python requirement.

- README.md
- docker-compose.yml
- modules/cron.py
Map `TZ` variable from `.env` and print the current time and time zone on `!cron time` command.
> Add Time Zone Environment Variable and cron time Command

- modules/cmd.py
Due to the immense power this module can provide, it shouldn't be enabled per default.
> Don't enable cmd module by default

- modules/url.py
From: https://github.com/encode/httpx/blob/master/CHANGELOG.md#0150-september-22nd-2020
> The verbose httpx.Timeout(5.0, connect_timeout=60.0) style had previously been deprecated in favour of httpx.Timeout(5.0, connect=60.0). It is now fully removed.
> Fix timeout definition

- README.md
- bot.py
- modules/alias.py
- modules/common/module.py
Use cases:
- A `!quotes` module which takes a name as its first argument can be called by `!name` instead of just `!quotes name` ([example](https://github.com/xPMo/hemppa-bot/blob/a783ad99e1c9c5ccc77f55938f5288ae44f017a7/modules/quote.py#L26))
- A module can provide multiple commands which share the same state ([example](https://github.com/xPMo/hemppa-bot/blob/a783ad99e1c9c5ccc77f55938f5288ae44f017a7/modules/show.py#L21))
Thanks for hemppa!
> Allow a module to declare aliases

- modules/pt.py
The PeerTube instance I was testing with did not return url property with videos.
> Fall back to video['uuid'] if video['url'] doesn't exist

- modules/alias.py
- modules/bot.py
- modules/common/module.py
- modules/help.py
- modules/room.py
- modules/wa.py
For #127
- Adds long_help via `!help [cmd]` and `module.long_help(**kwargs)`.
- Adds long_help(**kwargs) for some commands, and for those it only shows the subcommands that the event.sender can run.
- Adds `!sethelp msg true` to reply to !help requests with a dm instead of to the room. 
Needs review, I don't know how idiomatic the current `**kwargs` implementation is, or the way I am building strings is. My rationale for using kwargs is if a user wanted to write a long_help() which just returns a static string, they can just write it as `long_help(self, **kwargs): return 'string'` and not have to worry about the optional arguments passed to it.
> Enhancing !help

- modules/alias.py
With my !eval module, the "- {alias} => {name}" format was really long,
so here I invert the dictionary to shorten it up considerably.
Example:
```
Aliases:
- quote = 8ball, allan, angela, chris, rms, test, eight_ball, fauxang, angpaddle, chrislas
- show = live
- eval = python3, py3, python, hs, ghc, zsh, py, haskell, nim, nimdebug, evalpython3, evalpy3, evalpython, evalhs, evalghc, evalzsh, evalpy, evalhaskell, evalnim, evalnimdebug
- suggest = suggestsetup, suggestapikey
- pt = ptall
- wa = wafull
- help = sethelp
- loc = map, osm
```
> Use a shorter alias list

- modules/tautulli.py
- Lock on send_entry added to enforce that image and text for a single notification are sent atomically
- pms.get_image() can return `NoneType` object, check on it before unpacking (also better variables naming)
> Lock in send_entry and safe unpack on pms.get_image

- modules/tautulli.py
if `entry["art"]` is empty `pms.get_image` will return `None` and previous implementation would return without sending any notification
Now at lest the text notification without image will be sent
> Send only text notification without art

- README.md
- bot.py
- modules/bot.py
Closes #48 
TODO:
Possible additions, I'm not considering these right now:
> Print recent logs with !bot logs

- README.md
- bot.py
- modules/apod.py
- modules/bot.py
- modules/tautulli.py
!apod was expected upload_and_send to return a uri for it to cache. Instead, have bot.upload handle caching.
- Move matrix_uri_cache idea from apod into global bot, persist on restart
- ~~TODO:~~ add "!bot uricache [ view | clean ]" command
@aspacca please let me know if this breaks any of your modules. I'm fairly certain it won't, but I don't use them myself.
> Change bot.upload_and_send() and !apod

- modules/help.py
This PR allows customizing the info line at the end of `!help` with `!sethelp info [TEXT]`.
Example:
```
!sethelp info More information at https://github.com/vranki/hemppa. Leave your feedback at #hemppa:hacklab.fi.
```
```
This is Hemppa 1.5, a generic Matrix bot. Known commands:
- !cron: Runs scheduled commands
- !echo: Echoes back what user has said
<...>
- !help: Prints help on commands
More information at https://github.com/vranki/hemppa. Leave your feedback at #hemppa:hacklab.fi.
```
> !sethelp info and more

- .github/dependabot.yml
- .github/workflows/docker-publish.yml
This adds a dependabot-thing that will automatically create pull-requests with updates to any github actions that might need updating.
I also included the latest actions it would do.
dependabot also supports checking Dockerfile, and other software - but I haven't touched those.
> Update github actions, add dependabot to handle future updates

- bot.py
When uploading a blob, upload fails due to filesize= being a required parameter. This fixes the issue.
Discovered when attempting bot.upload_and_send_image(room, binary_content, text, True)
> Bugfix: filesize required for AsyncClient upload

- README.md
- bot.py
- modules/apod.py
Making this a PR because I want a second tester to make sure I didn't break anything in refactoring image uploading.
The main purpose of refactoring was to make `upload_and_send_image` less necessary. There was a decent amount of boilerplate needed to do `upload_image` then `send_image`. Since now `upload_image` then `set_room_avatar` is an option, I want to make calling those two functions subsequently as easy as possible.
To do all four: (check cache, attempt to upload, send image, and set avatar), `!apod` now does this:
```py
mxc_details = bot.get_uri_cache(apod.hdurl)
try:
if not mxc_details:
mxc_details = await self.upload_image(apod.hdurl, blob=blob)
matrix_uri, mimetype, w, h, size = mxc_details
await bot.send_image(room, matrix_uri, apod.hdurl, mimetype, w, h, size)
if …
```
> Support room avatar, and refactor image uploading

- README.md
- modules/ghproj.py
Purpose: Allow array of colors per domain
New JSON format example: 
`domains={"koneet":["#BFDADC","#0CBBF0","#0CBBF0","#E15D19","#ED49CF"],"tilat":["#0E8A16","#1E8A16"]}`
> Allow array of colors per domain

- README.md
- bot.py
- Wrap bot.client.room_send() to modify outgoing messages based on
pre_event
- Test for existence of m.relates_to
- Add event parameter to all module's uses of send_(text|html|...)
Fixes #192
> Support m.thread:

- README.md
- bot.py
- modules/apod.py
- modules/common/exceptions.py
- modules/printing.py
- modules/tautulli.py
I've pulled from master since a long while and start experiencing aiohttp in the tautulli module listing twice on the same port
After many changes to the tautulli module I've identified the follwoing:
https://github.com/vranki/hemppa/commit/bdc9713a146fce0339f40e8486c1b512657f27de#diff-15c4a2d5065f85d9cf3c0cefaa1e3269d5c43fe2aa965981ecf3c50d71c7230bR9
Importing `UploadFailed` from `bot` made the bot to be started twice
you should be able to see the following then starting the bot:
```
2022-08-14 22:37:57,433 - INFO - hemppa - Loading module: apod..
Traceback (most recent call last):
File "/opt/hemppa/bot.py", line 678, in <module>
asyncio.run(main())
File "/usr/lib/python3.10/asyncio/runners.py", line 33, in run
raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a …
```
> fix Bot running twice and refactor tautulli module

- modules/tautulli.py
I removed the `asyncio.lock()` in the tautulli module in the last refactoring, but that's indeed wrong. when multiple notifications happen at very short distance the order of image art and notification content will be wrong as well without it
> the order matters

- README.md
- bot.py
Added an optional .env variable which allows homeserver only opteration of the bot. Even when `join_on_invite=true`, the bot will not join rooms which are located elsewhere than its own homeserver.
The idea is to prevent malicious external use of the bot.
> add homeserver_only option

- README.md
- modules/nitter.py
- modules/twitter.py
Reads Twitter links from room, replaces domain with nitter, removes query parameters and posts link to room.
* !twitter enable     - enable converting twitter links to nitter links in this room (must be done as room admin)
* !twitter disable    - disable converting twitter links to nitter links in this room (must be done as room admin)
Additional improvements: allow changing of which nitter fediverse proxy is used for the replacement link. If user's message to room is only a twitter link and bot is admin, remove the post and post the replaced nitter link.
> Twitter module initial commit
